doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            # Mapped superclass for refresh tokens (gesdinet/jwt-refresh-token-bundle)
            GesdinetJWTRefreshTokenBundle:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/vendor/gesdinet/jwt-refresh-token-bundle/config/doctrine'
                prefix: 'Gesdinet\JWTRefreshTokenBundle\Entity'
                alias: GesdinetJWTRefreshTokenBundle
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Infrastructure/Persistence'
                prefix: 'App\User\Infrastructure\Persistence'
                alias: User
            Tweet:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Tweet/Infrastructure/Persistence'
                prefix: 'App\Tweet\Infrastructure\Persistence'
                alias: Tweet
            Like:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Like/Infrastructure/Persistence'
                prefix: 'App\Like\Infrastructure\Persistence'
                alias: Like
            Follow:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Follow/Infrastructure/Persistence'
                prefix: 'App\Follow\Infrastructure\Persistence'
                alias: Follow

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
